# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordCount', '0002_auto_20200530_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcount',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wordcount',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
