# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-30 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordCount', '0003_auto_20200530_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcount',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
