# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-31 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordCount', '0007_auto_20200530_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordcount',
            old_name='result',
            new_name='lines',
        ),
        migrations.AddField(
            model_name='wordcount',
            name='words',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
