# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordCount', '0008_auto_20200531_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='lines',
            field=models.CharField(max_length=100),
        ),
    ]
